### ISSUE TITLE
Adding handling of parenthesis

### ISSUE THREAD

**Issue by aubertc** [peterbro1/RCCS_Impl#7]
Right now, 

```
a.P + b.Q | b.C
```

is parsed as

```
(a.P+(b.Q|b.C))
```

but there should be a way of entering the process (a.P + b.Q) | b.C.

**Comment by peterbro1** [comment]
542ce1dd724e4aac02b04d711ef797ed08dee56d

I just added the first iteration of parenthesis parsing. It's been a busy day at work, so I have not had a long time to mess with it, but it works for (at least) for now

**Comment by aubertc** [comment]
Excellent. I have made [a brief comment](https://github.com/peterbro1/RCCS_Impl/commit/542ce1dd724e4aac02b04d711ef797ed08dee56d#commitcomment-68697414) and [updated an issue](https://github.com/peterbro1/RCCS_Impl/issues/9#issuecomment-1067510858) as an answer. 

Thanks for this progress!

**Comment by peterbro1** [comment]
Parenthesis is now stable, and can pass redundant parenthesis tests
